CREATE TABLE customer (
  customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(100) NOT NULL,
  email VARCHAR2(100) NOT NULL,
  mobile_number VARCHAR2(20) NOT NULL,
  pwd VARCHAR2(500) NOT NULL,
  role VARCHAR2(100) NOT NULL,
  create_dt DATE DEFAULT NULL
);

INSERT INTO customer (name, email, mobile_number, pwd, role, create_dt)
VALUES ('Happy', 'happy@example.com', '9876548337', '$2y$12$oRRbkNfwuR8ug4MlzH5FOeui.//1mkd.RsOAJMbykTSupVy.x/vb2', 'admin', SYSDATE);

CREATE TABLE accounts (
  customer_id NUMBER NOT NULL,
  account_number NUMBER NOT NULL,
  account_type VARCHAR2(100) NOT NULL,
  branch_address VARCHAR2(200) NOT NULL,
  create_dt DATE DEFAULT NULL,
  PRIMARY KEY (account_number),
  CONSTRAINT fk_customer_id FOREIGN KEY (customer_id) REFERENCES customer (customer_id) ON DELETE CASCADE
);

INSERT INTO accounts (customer_id, account_number, account_type, branch_address, create_dt)
VALUES (1, 1865764534, 'Savings', '123 Main Street, New York', SYSDATE);

CREATE TABLE account_transactions (
  transaction_id VARCHAR2(200) NOT NULL,
  account_number NUMBER NOT NULL,
  customer_id NUMBER NOT NULL,
  transaction_dt DATE NOT NULL,
  transaction_summary VARCHAR2(200) NOT NULL,
  transaction_type VARCHAR2(100) NOT NULL,
  transaction_amt NUMBER NOT NULL,
  closing_balance NUMBER NOT NULL,
  create_dt DATE DEFAULT NULL,
  PRIMARY KEY (transaction_id),
  CONSTRAINT fk_account_number FOREIGN KEY (account_number) REFERENCES accounts (account_number) ON DELETE CASCADE,
  CONSTRAINT fk_customer_id2 FOREIGN KEY (customer_id) REFERENCES customer (customer_id) ON DELETE CASCADE
);

-- Insert statements for account_transactions...

CREATE TABLE loans (
  loan_number NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id NUMBER NOT NULL,
  start_dt DATE NOT NULL,
  loan_type VARCHAR2(100) NOT NULL,
  total_loan NUMBER NOT NULL,
  amount_paid NUMBER NOT NULL,
  outstanding_amount NUMBER NOT NULL,
  create_dt DATE DEFAULT NULL,
  CONSTRAINT fk_customer_id3 FOREIGN KEY (customer_id) REFERENCES customer (customer_id) ON DELETE CASCADE
);

-- Insert statements for loans...

CREATE TABLE cards (
  card_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  card_number VARCHAR2(100) NOT NULL,
  customer_id NUMBER NOT NULL,
  card_type VARCHAR2(100) NOT NULL,
  total_limit NUMBER NOT NULL,
  amount_used NUMBER NOT NULL,
  available_amount NUMBER NOT NULL,
  create_dt DATE DEFAULT NULL,
  CONSTRAINT fk_customer_id4 FOREIGN KEY (customer_id) REFERENCES customer (customer_id) ON DELETE CASCADE
);

-- Insert statements for cards...

CREATE TABLE notice_details (
  notice_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  notice_summary VARCHAR2(200) NOT NULL,
  notice_details VARCHAR2(500) NOT NULL,
  notic_beg_dt DATE NOT NULL,
  notic_end_dt DATE DEFAULT NULL,
  create_dt DATE DEFAULT NULL,
  update_dt DATE DEFAULT NULL
);

-- Insert statements for notice_details...

CREATE TABLE contact_messages (
  contact_id VARCHAR2(50) NOT NULL,
  contact_name VARCHAR2(50) NOT NULL,
  contact_email VARCHAR2(100) NOT NULL,
  subject VARCHAR2(500) NOT NULL,
  message VARCHAR2(2000) NOT NULL,
  create_dt DATE DEFAULT NULL,
  PRIMARY KEY (contact_id)
);

-- Insert statements for contact_messages...

CREATE TABLE authorities (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id NUMBER NOT NULL,
  name VARCHAR2(50) NOT NULL,
  CONSTRAINT fk_customer_id5 FOREIGN KEY (customer_id) REFERENCES customer (customer_id)
);

DELETE FROM authorities;

INSERT INTO authorities (customer_id, name) VALUES (1, 'VIEWACCOUNT');
INSERT INTO authorities (customer_id, name) VALUES (1, 'VIEWCARDS');
INSERT INTO authorities (customer_id, name) VALUES (1, 'VIEWLOANS');
INSERT INTO authorities (customer_id, name) VALUES (1, 'VIEWBALANCE');
INSERT INTO authorities (customer_id, name) VALUES (1, 'ROLE_USER');
INSERT INTO authorities (customer_id, name) VALUES (1, 'ROLE_ADMIN');
